version: '3'
services:
  app:
    build: 
      context: ./

    networks:
      - internal

    env_file:
      - .env
    ports:
      - 9007:9007

    volumes:
      - vol_mysql_data:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  vol_storage:
    driver: local
  vol_mysql_data:
    driver: local
